"""
scripts/generate_synthetic_pairs.py

Builds a DualEDSR dataset where:

    - TRAINING   uses a SYNTHETIC LR volume, generated by degrading
                 (blur + downsample) the full real HR volume.
    - VALIDATION uses the REAL registered LR/HR pair -- the genuine
                 low-resolution scan (ffov_crop_origsize.tiff) paired
                 with the genuine high-resolution scan
                 (PEFC_hres_0p7um.tiff), exactly as acquired.

No train/validation splitting is performed on either volume -- there is
only one real HR volume, and it is used in full both as the training
target (paired with its synthetic LR) and as the validation target
(paired with the real LR).

Output layout:

    data/processed/Wang_2023_synthetic/training/HR/HR.npy    <- real HR (full volume)
    data/processed/Wang_2023_synthetic/training/LR/LR.npy    <- synthetic LR (degraded from HR above)
    data/processed/Wang_2023_synthetic/validation/HR/HR.npy  <- real HR (same full volume, saved again)
    data/processed/Wang_2023_synthetic/validation/LR/LR.npy  <- real LR (genuine low-res scan)

Why reuse the same HR volume for both training and validation targets
------------------------------------------------------------------------
This is intentional, not an oversight. There is only one real HR volume
available, so it has to serve as ground truth on both sides. The point
of keeping it identical in both places is to make the comparison
apples-to-apples: after training the network to map (synthetic LR) ->
(HR), validation checks whether the SAME network, given the (real LR)
of that SAME region, still reconstructs that SAME HR. If it does, the
synthetic degradation model used for training is realistic enough to
transfer to genuine scans. If it doesn't, that gap tells you BLUR_SIGMA
(or the degradation model in general) needs to be recalibrated -- see
the note below.

IMPORTANT -- calibrate BLUR_SIGMA before trusting this data
--------------------------------------------------------------
Downsampling alone produces an LR volume that is unrealistically sharp
compared to a real low-resolution micro-CT scan (real acquisitions are
also blurred by the optics/detector, not just spatially coarser).
BLUR_SIGMA=1.0 below is only a starting point. Since this script also
processes the real LR volume, you can compare it directly against the
synthetic training LR (same underlying HR region) to judge whether
BLUR_SIGMA needs adjusting -- e.g. compare histograms, edge sharpness, or
a power spectrum of validation/LR/LR.npy vs. training/LR/LR.npy.

Usage (from the repo root, after downloading the raw tiffs):
    python scripts/generate_synthetic_pairs.py
"""

import sys
from pathlib import Path

import numpy as np
import tifffile

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from src import preprocessing

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------
RAW_DIR = Path("data/raw/Wang_2023")
OUT_DIR = Path("data/processed/Wang_2023_synthetic")

LR_RAW = RAW_DIR / "ffov_crop_origsize.tiff"
HR_RAW = RAW_DIR / "PEFC_hres_0p7um.tiff"

# --- HR target shape --------------------------------------------------
HR_TARGET_SHAPE = (600, 600, 900)

# --- synthetic LR (training): derived from HR by blur + downsample ----
SCALE_FACTOR = 4  # same S used in the original DualEDSR paper
LR_TARGET_SHAPE = tuple(s // SCALE_FACTOR for s in HR_TARGET_SHAPE)  # (150, 150, 225)
BLUR_SIGMA = 1.0  # voxels, in HR space -- STARTING POINT ONLY, see note above

# --- real LR (validation): voxel-size correction before crop ----------
VOXEL_SIZE_LR_ORIGINAL_UM = 4.2
VOXEL_SIZE_LR_TARGET_UM = 2.8
LR_VOXEL_CORRECTION_FACTOR = VOXEL_SIZE_LR_ORIGINAL_UM / VOXEL_SIZE_LR_TARGET_UM  # 1.5x

VISUAL_CHECK_DIR = OUT_DIR / "visual_check"


def section(title):
    print("\n" + "=" * 60)
    print(title)
    print("=" * 60)


def process_real_hr():
    """Loads and prepares the real HR volume in full (no split). Used as
    the ground-truth target for BOTH training (paired with a synthetic
    LR) and validation (paired with the real LR)."""
    assert HR_RAW.exists(), f"HR raw file not found: {HR_RAW} (run scripts/Wang_2023_load_raw_data.sh first)"
    assert all(h % SCALE_FACTOR == 0 for h in HR_TARGET_SHAPE), (
        f"HR_TARGET_SHAPE {HR_TARGET_SHAPE} must be evenly divisible by "
        f"SCALE_FACTOR ({SCALE_FACTOR}) in every axis."
    )

    section("Processing real HR (PEFC_hres_0p7um.tiff)")
    hr_npy = preprocessing.convert_ftype(HR_RAW, "npy", output_path=OUT_DIR / "_steps" / "HR_01_npy.npy")
    print(f"  1. .tiff -> .npy:        {hr_npy.shape}, {hr_npy.dtype}")

    hr_npy = preprocessing.TrackedArray(hr_npy.transpose(1, 2, 0), source_path=hr_npy.source_path)
    print(f"     (transposed [Z,Y,X] -> [Y,X,Z]): {hr_npy.shape}")

    hr_uint8 = preprocessing.convert_dtype(hr_npy, np.uint8, output_path=OUT_DIR / "_steps" / "HR_02_uint8.npy")
    print(f"  2. uint16 -> uint8:      {hr_uint8.shape}, {hr_uint8.dtype}")

    hr_cropped = preprocessing.center_crop(
        hr_uint8, size=HR_TARGET_SHAPE,
        output_path=OUT_DIR / "_steps" / "HR_03_cropped.npy",
    )
    print(f"  3. center_crop:          {hr_cropped.shape}  (target: {HR_TARGET_SHAPE})")

    return hr_cropped


def generate_synthetic_lr(hr_volume):
    """TRAINING LR: degrades the real HR volume into a synthetic LR
    volume (blur, then downsample by 1/SCALE_FACTOR)."""
    section("Generating synthetic LR from HR (blur + downsample) -- for TRAINING")
    blurred = preprocessing.gaussian_blur(
        hr_volume, sigma=BLUR_SIGMA,
        output_path=OUT_DIR / "_steps" / "LR_synthetic_01_blurred.npy",
    )
    print(f"  1. gaussian_blur (sigma={BLUR_SIGMA}): {blurred.shape}")

    lr_synthetic = preprocessing.cubic_interpolation(
        blurred, target_shape=LR_TARGET_SHAPE,
        output_path=OUT_DIR / "_steps" / "LR_synthetic_02_downsampled.npy",
    )
    print(f"  2. downsample:           {lr_synthetic.shape}  (target: {LR_TARGET_SHAPE})")

    return lr_synthetic


def process_real_lr():
    """VALIDATION LR: loads and prepares the real, genuinely-acquired
    low-resolution volume (voxel-size correction + crop), exactly as the
    original Wang_2023_process_data.py did."""
    assert LR_RAW.exists(), f"LR raw file not found: {LR_RAW} (run scripts/Wang_2023_load_raw_data.sh first)"

    section("Processing real LR (ffov_crop_origsize.tiff) -- for VALIDATION")
    lr_npy = preprocessing.convert_ftype(LR_RAW, "npy", output_path=OUT_DIR / "_steps" / "LR_real_01_npy.npy")
    print(f"  1. .tiff -> .npy:        {lr_npy.shape}, {lr_npy.dtype}")

    lr_npy = preprocessing.TrackedArray(lr_npy.transpose(1, 2, 0), source_path=lr_npy.source_path)
    print(f"     (transposed [Z,Y,X] -> [Y,X,Z]): {lr_npy.shape}")

    lr_uint8 = preprocessing.convert_dtype(lr_npy, np.uint8, output_path=OUT_DIR / "_steps" / "LR_real_02_uint8.npy")
    print(f"  2. uint16 -> uint8:      {lr_uint8.shape}, {lr_uint8.dtype}")

    lr_upsampled = preprocessing.cubic_interpolation(
        lr_uint8, scale_factor=LR_VOXEL_CORRECTION_FACTOR,
        output_path=OUT_DIR / "_steps" / "LR_real_03_upsampled.npy",
    )
    print(f"  3. voxel-size correction ({LR_VOXEL_CORRECTION_FACTOR:.2f}x): {lr_upsampled.shape}")

    lr_cropped = preprocessing.center_crop(
        lr_upsampled, size=LR_TARGET_SHAPE,
        output_path=OUT_DIR / "_steps" / "LR_real_04_cropped.npy",
    )
    print(f"  4. center_crop:          {lr_cropped.shape}  (target: {LR_TARGET_SHAPE})")

    return lr_cropped


def prepare_data():
    """Runs the full pipeline and saves the final training/validation
    .npy files. Returns the dict of final {path: array} pairs, for reuse
    by export_for_visual_check."""
    hr_real = process_real_hr()
    lr_synthetic = generate_synthetic_lr(hr_real)
    lr_real = process_real_lr()

    section("Saving final files")
    final_paths = {
        OUT_DIR / "training" / "HR" / "HR.npy": hr_real,
        OUT_DIR / "training" / "LR" / "LR.npy": lr_synthetic,
        OUT_DIR / "validation" / "HR" / "HR.npy": hr_real,
        OUT_DIR / "validation" / "LR" / "LR.npy": lr_real,
    }
    for path, array in final_paths.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        np.save(path, array)
        print(f"  {path}  (shape={array.shape}, dtype={array.dtype})")

    print(f"\nData preparation done. Final files ready under {OUT_DIR}/training/ and {OUT_DIR}/validation/")
    print(f"(Intermediate step files kept under {OUT_DIR}/_steps/ for inspection/traceability.)")
    print(f"\nReminder: BLUR_SIGMA={BLUR_SIGMA} is a starting guess -- compare training/LR/LR.npy "
          f"against validation/LR/LR.npy (same underlying region) and adjust it if they don't "
          f"look/behave similarly.")

    return final_paths


def export_for_visual_check(final_paths):
    """Converts the final prepared .npy files back to .tif, for visual
    inspection."""
    section("Exporting final files to .tif for visual inspection")

    for npy_path in final_paths:
        if not npy_path.exists():
            print(f"[SKIPPED] {npy_path} not found.")
            continue

        tag = f"{npy_path.parent.parent.name}_{npy_path.parent.name}"
        output_path = VISUAL_CHECK_DIR / f"{tag}.tif"

        volume = np.load(npy_path)
        volume_zyx = volume.transpose(2, 0, 1)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        tifffile.imwrite(output_path, volume_zyx)
        print(f"  {npy_path}  ->  {output_path}  (saved as [Z,Y,X]={volume_zyx.shape})")

    print(f"\nOpen the files under {VISUAL_CHECK_DIR}/ in ImageJ/Fiji or napari to inspect visually.")


def main():
    final_paths = prepare_data()
    export_for_visual_check(final_paths)


if __name__ == "__main__":
    main()